### PR TITLE
BUG: Fixed Factor Analysis lecture; scaling was off

### PR DESCRIPTION
**Pull request by mmargenot**
Fixes https://github.com/quantopian/research_public/issues/256

### CODE REVIEW

**Comment by jmccorriston** [comment]
image
--> 'is analyzed **in** different ways' (though this makes the next phrase sound awkward). in general, it might be helpful to be more explicit here instead of using 'this information'. What about something like "Alphalens provides three categories of analysis on alpha factors:"

**Comment by jmccorriston** [comment]
image
'!' --> '.'

**Comment by jmccorriston** [comment]
image
What does 'these point estimates' refer to here? wondering if it's referring to something the got cut in the change.

**Comment by jmccorriston** [comment]
answered my own question re 'these point estimates'. I see what it's referring to, but I think we should be explicit and call it 'the returns point estimates chart' or something equivalent, and I think we should do it for each plot.

**Comment by jmccorriston** [comment]
image
"a breakdown returns" --> "a breakdown of returns"
"feed it a set of classifiers" --> "feed it a set of industry labels"?

**Comment by mmargenot** [comment]
Alphalens is more general than just industry labels. I'll change it to `feed it a set of classifiers (such as industry labels)`.

**Comment by jmccorriston** [comment]
I'd recommend against the use of the word 'classifiers', since that means something specific in Pipeline. Maybe 'feed it a set of labels'?.

**Comment by jmccorriston** [comment]
image
maybe add 'relative to the total portfolio value' at the end of this sentence? or is it relative to the actual gross book value of the portfolio?

**Comment by mmargenot** [comment]
How about `categorical values`? Labels are a separate thing that you can include as a parameter.

**Comment by mmargenot** [comment]
The turnover has nothing to do with the value of the portfolio in Alphalens. It's just the percentage of names in the basket that have changed.

**Comment by jmccorriston** [comment]
'categorical values' works for me!

**Comment by jmccorriston** [comment]
I was definitely mixing up turnover in my head, oops! Other than being more explicit on the references to plots and tables, and the minor language tweaks above, looks good to me.

**Pull request merged**
